image: python:3.9-slim

# стейджи пайплайна
stages:
  - tasks # у этого стейджа есть стэпы: 'tasks from 3rd to 11th' & 'task 12th'

# внутри пайплайна автоматически поднимается
# пустая база Postgres (каждый раз на новый степ)
services:
  - name: postgres:15-alpine
    alias: postgres



variables:
#  переменные окружения для Postgres
  POSTGRES_DB: postgres
  POSTGRES_USER: postgres
  POSTGRES_PASSWORD: password
  POSTGRES_HOST_AUTH_METHOD: trust

#  переменные окружения для вспомогательного
#  скрипта utils/pypsql.py и тестов
  DBNAME: postgres
  DBHOST: postgres
  DBPORT: 5432
  DBUSER: postgres
  DBPASSWORD: password

#  аккуратное формирование всяких абсолютных
#  путей к файлам и директориям
#  у вас будет ${PROJECT_DIR} тождественно равен ${CI_PROJECT_DIR}
  PROJECT_DIR: ${CI_PROJECT_DIR}
  SCRIPTS_DIR: ${PROJECT_DIR}/scripts
  TESTS_DIR: ${PROJECT_DIR}/tests
  UTILS_DIR: ${PROJECT_DIR}/utils
  PYPSQL: ${UTILS_DIR}/pypsql.py

#  переменные для цвета в консоли (можете
#  использовать какие-то другие свои)
  NO_COLOUR: '\033[0m'
  LIGHT_RED: '\033[1;31m'


.setup:
  before_script:
    - pip install -r ${PROJECT_DIR}/requirements.txt > /dev/null 2> /dev/null


tasks from 3rd to 11th:
  stage: tasks
  extends:
    - .setup
  script:
    - echo -e "${LIGHT_RED}>>> Task №3 <<<${NO_COLOUR}"

    - python3 ${PYPSQL} --file="${SCRIPTS_DIR}/vault_ddl.sql" --cat


    - echo -e "${LIGHT_RED}>>> Task №4-5 <<<${NO_COLOUR}"


    - python3 ${PYPSQL} --file="${SCRIPTS_DIR}/vault_inserts.sql"
    - echo "Table 'cd.animal' contains rows:"

    - python3 ${PYPSQL} --sql="SELECT * FROM cd.medicine" --verbose
    - echo "Table 'cd.medicine' contains rows:"

    - python3 ${PYPSQL} --sql="SELECT * FROM cd.provisions" --verbose
    - echo "Table 'cd.provisions' contains rows:"

    - python3 ${PYPSQL} --sql="SELECT * FROM cd.appliance" --verbose
    - echo "Table 'cd.appliance' contains rows:"

    - python3 ${PYPSQL} --sql="SELECT * FROM cd.bedroom" --verbose
    - echo "Table 'cd.bedroom' contains rows:"

    - python3 ${PYPSQL} --sql="SELECT * FROM cd.person" --verbose
    - echo "Table 'cd.person' contains rows:"

    - python3 ${PYPSQL} --sql="SELECT * FROM cd.task" --verbose
    - echo "Table 'cd.task' contains rows:"

    - python3 ${PYPSQL} --sql="SELECT * FROM cd.actual_tasks" --verbose
    - echo "Table 'cd.actual_tasks' contains rows:"

    - python3 ${PYPSQL} --sql="SELECT * FROM cd.task_history" --verbose
    - echo "Table 'cd.task_history' contains rows:"

    - python3 ${PYPSQL} --sql="SELECT * FROM cd.sleep_schedule" --verbose
    - echo "Table 'cd.sleep_schedule' contains rows:"



    - echo -e "${LIGHT_RED}>>> Task №6-7 <<<${NO_COLOUR}"
    - SCRIPT_PATH="${SCRIPTS_DIR}/select_count_tables.sql" pytest ${TESTS_DIR}/test_select_count.py

    - echo -e "${LIGHT_RED}>>> Task №9 <<<${NO_COLOUR}"

    - echo -e "${LIGHT_RED}>>> Task №10 <<<${NO_COLOUR}"


task 12th:
  stage: tasks
  extends:
    - .setup
  script:
    - python3 ${PYPSQL} --file="${SCRIPTS_DIR}/vault_ddl.sql"

